//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	networkingv1beta1 "k8s.io/api/networking/v1beta1"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	corev1 "github.com/zoetrope/ac-deepcopy/applyconfigurations/core/v1"
	v1 "github.com/zoetrope/ac-deepcopy/applyconfigurations/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPIngressPathApplyConfiguration) DeepCopyInto(out *HTTPIngressPathApplyConfiguration) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.PathType != nil {
		in, out := &in.PathType, &out.PathType
		*out = new(networkingv1beta1.PathType)
		**out = **in
	}
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(IngressBackendApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPIngressPathApplyConfiguration.
func (in *HTTPIngressPathApplyConfiguration) DeepCopy() *HTTPIngressPathApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(HTTPIngressPathApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPIngressRuleValueApplyConfiguration) DeepCopyInto(out *HTTPIngressRuleValueApplyConfiguration) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]HTTPIngressPathApplyConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPIngressRuleValueApplyConfiguration.
func (in *HTTPIngressRuleValueApplyConfiguration) DeepCopy() *HTTPIngressRuleValueApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(HTTPIngressRuleValueApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressApplyConfiguration) DeepCopyInto(out *IngressApplyConfiguration) {
	*out = *in
	in.TypeMetaApplyConfiguration.DeepCopyInto(&out.TypeMetaApplyConfiguration)
	if in.ObjectMetaApplyConfiguration != nil {
		in, out := &in.ObjectMetaApplyConfiguration, &out.ObjectMetaApplyConfiguration
		*out = new(v1.ObjectMetaApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(IngressSpecApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(IngressStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressApplyConfiguration.
func (in *IngressApplyConfiguration) DeepCopy() *IngressApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressBackendApplyConfiguration) DeepCopyInto(out *IngressBackendApplyConfiguration) {
	*out = *in
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.ServicePort != nil {
		in, out := &in.ServicePort, &out.ServicePort
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(corev1.TypedLocalObjectReferenceApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressBackendApplyConfiguration.
func (in *IngressBackendApplyConfiguration) DeepCopy() *IngressBackendApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressBackendApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressClassApplyConfiguration) DeepCopyInto(out *IngressClassApplyConfiguration) {
	*out = *in
	in.TypeMetaApplyConfiguration.DeepCopyInto(&out.TypeMetaApplyConfiguration)
	if in.ObjectMetaApplyConfiguration != nil {
		in, out := &in.ObjectMetaApplyConfiguration, &out.ObjectMetaApplyConfiguration
		*out = new(v1.ObjectMetaApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(IngressClassSpecApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressClassApplyConfiguration.
func (in *IngressClassApplyConfiguration) DeepCopy() *IngressClassApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressClassApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressClassParametersReferenceApplyConfiguration) DeepCopyInto(out *IngressClassParametersReferenceApplyConfiguration) {
	*out = *in
	if in.APIGroup != nil {
		in, out := &in.APIGroup, &out.APIGroup
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressClassParametersReferenceApplyConfiguration.
func (in *IngressClassParametersReferenceApplyConfiguration) DeepCopy() *IngressClassParametersReferenceApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressClassParametersReferenceApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressClassSpecApplyConfiguration) DeepCopyInto(out *IngressClassSpecApplyConfiguration) {
	*out = *in
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(IngressClassParametersReferenceApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressClassSpecApplyConfiguration.
func (in *IngressClassSpecApplyConfiguration) DeepCopy() *IngressClassSpecApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressClassSpecApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressRuleApplyConfiguration) DeepCopyInto(out *IngressRuleApplyConfiguration) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	in.IngressRuleValueApplyConfiguration.DeepCopyInto(&out.IngressRuleValueApplyConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressRuleApplyConfiguration.
func (in *IngressRuleApplyConfiguration) DeepCopy() *IngressRuleApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressRuleApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressRuleValueApplyConfiguration) DeepCopyInto(out *IngressRuleValueApplyConfiguration) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPIngressRuleValueApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressRuleValueApplyConfiguration.
func (in *IngressRuleValueApplyConfiguration) DeepCopy() *IngressRuleValueApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressRuleValueApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpecApplyConfiguration) DeepCopyInto(out *IngressSpecApplyConfiguration) {
	*out = *in
	if in.IngressClassName != nil {
		in, out := &in.IngressClassName, &out.IngressClassName
		*out = new(string)
		**out = **in
	}
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(IngressBackendApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]IngressTLSApplyConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]IngressRuleApplyConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpecApplyConfiguration.
func (in *IngressSpecApplyConfiguration) DeepCopy() *IngressSpecApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressSpecApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressStatusApplyConfiguration) DeepCopyInto(out *IngressStatusApplyConfiguration) {
	*out = *in
	if in.LoadBalancer != nil {
		in, out := &in.LoadBalancer, &out.LoadBalancer
		*out = new(corev1.LoadBalancerStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressStatusApplyConfiguration.
func (in *IngressStatusApplyConfiguration) DeepCopy() *IngressStatusApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressStatusApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTLSApplyConfiguration) DeepCopyInto(out *IngressTLSApplyConfiguration) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTLSApplyConfiguration.
func (in *IngressTLSApplyConfiguration) DeepCopy() *IngressTLSApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressTLSApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}
