//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "github.com/zoetrope/ssa-helper/applyconfigurations/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseApplyConfiguration) DeepCopyInto(out *LeaseApplyConfiguration) {
	*out = *in
	in.TypeMetaApplyConfiguration.DeepCopyInto(&out.TypeMetaApplyConfiguration)
	if in.ObjectMetaApplyConfiguration != nil {
		in, out := &in.ObjectMetaApplyConfiguration, &out.ObjectMetaApplyConfiguration
		*out = new(v1.ObjectMetaApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(LeaseSpecApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseApplyConfiguration.
func (in *LeaseApplyConfiguration) DeepCopy() *LeaseApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(LeaseApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseSpecApplyConfiguration) DeepCopyInto(out *LeaseSpecApplyConfiguration) {
	*out = *in
	if in.HolderIdentity != nil {
		in, out := &in.HolderIdentity, &out.HolderIdentity
		*out = new(string)
		**out = **in
	}
	if in.LeaseDurationSeconds != nil {
		in, out := &in.LeaseDurationSeconds, &out.LeaseDurationSeconds
		*out = new(int32)
		**out = **in
	}
	if in.AcquireTime != nil {
		in, out := &in.AcquireTime, &out.AcquireTime
		*out = (*in).DeepCopy()
	}
	if in.RenewTime != nil {
		in, out := &in.RenewTime, &out.RenewTime
		*out = (*in).DeepCopy()
	}
	if in.LeaseTransitions != nil {
		in, out := &in.LeaseTransitions, &out.LeaseTransitions
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseSpecApplyConfiguration.
func (in *LeaseSpecApplyConfiguration) DeepCopy() *LeaseSpecApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(LeaseSpecApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}
