//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v2beta2

import (
	metav1 "github.com/zoetrope/ac-deepcopy/applyconfigurations/meta/v1"
	autoscalingv2beta2 "k8s.io/api/autoscaling/v2beta2"
	v1 "k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceMetricSourceApplyConfiguration) DeepCopyInto(out *ContainerResourceMetricSourceApplyConfiguration) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(v1.ResourceName)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(MetricTargetApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceMetricSourceApplyConfiguration.
func (in *ContainerResourceMetricSourceApplyConfiguration) DeepCopy() *ContainerResourceMetricSourceApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceMetricSourceApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceMetricStatusApplyConfiguration) DeepCopyInto(out *ContainerResourceMetricStatusApplyConfiguration) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(v1.ResourceName)
		**out = **in
	}
	if in.Current != nil {
		in, out := &in.Current, &out.Current
		*out = new(MetricValueStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceMetricStatusApplyConfiguration.
func (in *ContainerResourceMetricStatusApplyConfiguration) DeepCopy() *ContainerResourceMetricStatusApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceMetricStatusApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossVersionObjectReferenceApplyConfiguration) DeepCopyInto(out *CrossVersionObjectReferenceApplyConfiguration) {
	*out = *in
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossVersionObjectReferenceApplyConfiguration.
func (in *CrossVersionObjectReferenceApplyConfiguration) DeepCopy() *CrossVersionObjectReferenceApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(CrossVersionObjectReferenceApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalMetricSourceApplyConfiguration) DeepCopyInto(out *ExternalMetricSourceApplyConfiguration) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(MetricIdentifierApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(MetricTargetApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalMetricSourceApplyConfiguration.
func (in *ExternalMetricSourceApplyConfiguration) DeepCopy() *ExternalMetricSourceApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExternalMetricSourceApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalMetricStatusApplyConfiguration) DeepCopyInto(out *ExternalMetricStatusApplyConfiguration) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(MetricIdentifierApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Current != nil {
		in, out := &in.Current, &out.Current
		*out = new(MetricValueStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalMetricStatusApplyConfiguration.
func (in *ExternalMetricStatusApplyConfiguration) DeepCopy() *ExternalMetricStatusApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExternalMetricStatusApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPAScalingPolicyApplyConfiguration) DeepCopyInto(out *HPAScalingPolicyApplyConfiguration) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(autoscalingv2beta2.HPAScalingPolicyType)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(int32)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPAScalingPolicyApplyConfiguration.
func (in *HPAScalingPolicyApplyConfiguration) DeepCopy() *HPAScalingPolicyApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(HPAScalingPolicyApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPAScalingRulesApplyConfiguration) DeepCopyInto(out *HPAScalingRulesApplyConfiguration) {
	*out = *in
	if in.StabilizationWindowSeconds != nil {
		in, out := &in.StabilizationWindowSeconds, &out.StabilizationWindowSeconds
		*out = new(int32)
		**out = **in
	}
	if in.SelectPolicy != nil {
		in, out := &in.SelectPolicy, &out.SelectPolicy
		*out = new(autoscalingv2beta2.ScalingPolicySelect)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]HPAScalingPolicyApplyConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPAScalingRulesApplyConfiguration.
func (in *HPAScalingRulesApplyConfiguration) DeepCopy() *HPAScalingRulesApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(HPAScalingRulesApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPodAutoscalerApplyConfiguration) DeepCopyInto(out *HorizontalPodAutoscalerApplyConfiguration) {
	*out = *in
	in.TypeMetaApplyConfiguration.DeepCopyInto(&out.TypeMetaApplyConfiguration)
	if in.ObjectMetaApplyConfiguration != nil {
		in, out := &in.ObjectMetaApplyConfiguration, &out.ObjectMetaApplyConfiguration
		*out = new(metav1.ObjectMetaApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(HorizontalPodAutoscalerSpecApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(HorizontalPodAutoscalerStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPodAutoscalerApplyConfiguration.
func (in *HorizontalPodAutoscalerApplyConfiguration) DeepCopy() *HorizontalPodAutoscalerApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(HorizontalPodAutoscalerApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPodAutoscalerBehaviorApplyConfiguration) DeepCopyInto(out *HorizontalPodAutoscalerBehaviorApplyConfiguration) {
	*out = *in
	if in.ScaleUp != nil {
		in, out := &in.ScaleUp, &out.ScaleUp
		*out = new(HPAScalingRulesApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDown != nil {
		in, out := &in.ScaleDown, &out.ScaleDown
		*out = new(HPAScalingRulesApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPodAutoscalerBehaviorApplyConfiguration.
func (in *HorizontalPodAutoscalerBehaviorApplyConfiguration) DeepCopy() *HorizontalPodAutoscalerBehaviorApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(HorizontalPodAutoscalerBehaviorApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPodAutoscalerConditionApplyConfiguration) DeepCopyInto(out *HorizontalPodAutoscalerConditionApplyConfiguration) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(autoscalingv2beta2.HorizontalPodAutoscalerConditionType)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.ConditionStatus)
		**out = **in
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPodAutoscalerConditionApplyConfiguration.
func (in *HorizontalPodAutoscalerConditionApplyConfiguration) DeepCopy() *HorizontalPodAutoscalerConditionApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(HorizontalPodAutoscalerConditionApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPodAutoscalerSpecApplyConfiguration) DeepCopyInto(out *HorizontalPodAutoscalerSpecApplyConfiguration) {
	*out = *in
	if in.ScaleTargetRef != nil {
		in, out := &in.ScaleTargetRef, &out.ScaleTargetRef
		*out = new(CrossVersionObjectReferenceApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricSpecApplyConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(HorizontalPodAutoscalerBehaviorApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPodAutoscalerSpecApplyConfiguration.
func (in *HorizontalPodAutoscalerSpecApplyConfiguration) DeepCopy() *HorizontalPodAutoscalerSpecApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(HorizontalPodAutoscalerSpecApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPodAutoscalerStatusApplyConfiguration) DeepCopyInto(out *HorizontalPodAutoscalerStatusApplyConfiguration) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.CurrentReplicas != nil {
		in, out := &in.CurrentReplicas, &out.CurrentReplicas
		*out = new(int32)
		**out = **in
	}
	if in.DesiredReplicas != nil {
		in, out := &in.DesiredReplicas, &out.DesiredReplicas
		*out = new(int32)
		**out = **in
	}
	if in.CurrentMetrics != nil {
		in, out := &in.CurrentMetrics, &out.CurrentMetrics
		*out = make([]MetricStatusApplyConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]HorizontalPodAutoscalerConditionApplyConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPodAutoscalerStatusApplyConfiguration.
func (in *HorizontalPodAutoscalerStatusApplyConfiguration) DeepCopy() *HorizontalPodAutoscalerStatusApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(HorizontalPodAutoscalerStatusApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricIdentifierApplyConfiguration) DeepCopyInto(out *MetricIdentifierApplyConfiguration) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelectorApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricIdentifierApplyConfiguration.
func (in *MetricIdentifierApplyConfiguration) DeepCopy() *MetricIdentifierApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricIdentifierApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSpecApplyConfiguration) DeepCopyInto(out *MetricSpecApplyConfiguration) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(autoscalingv2beta2.MetricSourceType)
		**out = **in
	}
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(ObjectMetricSourceApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(PodsMetricSourceApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(ResourceMetricSourceApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerResource != nil {
		in, out := &in.ContainerResource, &out.ContainerResource
		*out = new(ContainerResourceMetricSourceApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalMetricSourceApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSpecApplyConfiguration.
func (in *MetricSpecApplyConfiguration) DeepCopy() *MetricSpecApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricSpecApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricStatusApplyConfiguration) DeepCopyInto(out *MetricStatusApplyConfiguration) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(autoscalingv2beta2.MetricSourceType)
		**out = **in
	}
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(ObjectMetricStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(PodsMetricStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(ResourceMetricStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerResource != nil {
		in, out := &in.ContainerResource, &out.ContainerResource
		*out = new(ContainerResourceMetricStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalMetricStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricStatusApplyConfiguration.
func (in *MetricStatusApplyConfiguration) DeepCopy() *MetricStatusApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricStatusApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricTargetApplyConfiguration) DeepCopyInto(out *MetricTargetApplyConfiguration) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(autoscalingv2beta2.MetricTargetType)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.AverageValue != nil {
		in, out := &in.AverageValue, &out.AverageValue
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.AverageUtilization != nil {
		in, out := &in.AverageUtilization, &out.AverageUtilization
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricTargetApplyConfiguration.
func (in *MetricTargetApplyConfiguration) DeepCopy() *MetricTargetApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricTargetApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricValueStatusApplyConfiguration) DeepCopyInto(out *MetricValueStatusApplyConfiguration) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.AverageValue != nil {
		in, out := &in.AverageValue, &out.AverageValue
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.AverageUtilization != nil {
		in, out := &in.AverageUtilization, &out.AverageUtilization
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricValueStatusApplyConfiguration.
func (in *MetricValueStatusApplyConfiguration) DeepCopy() *MetricValueStatusApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricValueStatusApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectMetricSourceApplyConfiguration) DeepCopyInto(out *ObjectMetricSourceApplyConfiguration) {
	*out = *in
	if in.DescribedObject != nil {
		in, out := &in.DescribedObject, &out.DescribedObject
		*out = new(CrossVersionObjectReferenceApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(MetricTargetApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(MetricIdentifierApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectMetricSourceApplyConfiguration.
func (in *ObjectMetricSourceApplyConfiguration) DeepCopy() *ObjectMetricSourceApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ObjectMetricSourceApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectMetricStatusApplyConfiguration) DeepCopyInto(out *ObjectMetricStatusApplyConfiguration) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(MetricIdentifierApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Current != nil {
		in, out := &in.Current, &out.Current
		*out = new(MetricValueStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.DescribedObject != nil {
		in, out := &in.DescribedObject, &out.DescribedObject
		*out = new(CrossVersionObjectReferenceApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectMetricStatusApplyConfiguration.
func (in *ObjectMetricStatusApplyConfiguration) DeepCopy() *ObjectMetricStatusApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ObjectMetricStatusApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodsMetricSourceApplyConfiguration) DeepCopyInto(out *PodsMetricSourceApplyConfiguration) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(MetricIdentifierApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(MetricTargetApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodsMetricSourceApplyConfiguration.
func (in *PodsMetricSourceApplyConfiguration) DeepCopy() *PodsMetricSourceApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(PodsMetricSourceApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodsMetricStatusApplyConfiguration) DeepCopyInto(out *PodsMetricStatusApplyConfiguration) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(MetricIdentifierApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Current != nil {
		in, out := &in.Current, &out.Current
		*out = new(MetricValueStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodsMetricStatusApplyConfiguration.
func (in *PodsMetricStatusApplyConfiguration) DeepCopy() *PodsMetricStatusApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(PodsMetricStatusApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceMetricSourceApplyConfiguration) DeepCopyInto(out *ResourceMetricSourceApplyConfiguration) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(v1.ResourceName)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(MetricTargetApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMetricSourceApplyConfiguration.
func (in *ResourceMetricSourceApplyConfiguration) DeepCopy() *ResourceMetricSourceApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ResourceMetricSourceApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceMetricStatusApplyConfiguration) DeepCopyInto(out *ResourceMetricStatusApplyConfiguration) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(v1.ResourceName)
		**out = **in
	}
	if in.Current != nil {
		in, out := &in.Current, &out.Current
		*out = new(MetricValueStatusApplyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMetricStatusApplyConfiguration.
func (in *ResourceMetricStatusApplyConfiguration) DeepCopy() *ResourceMetricStatusApplyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ResourceMetricStatusApplyConfiguration)
	in.DeepCopyInto(out)
	return out
}
